# Containerfile para el servicio api-server (validación de variables en runtime)

# Imagen base
FROM node:lts-alpine3.21

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar solo package.json y package-lock.json para caché inteligente
COPY ./server/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY ./server ./

# Copiar script de entrada para validar variables de entorno
# Asegúrate de colocar entrypoint.sh dentro de la carpeta 'server' para incluirlo en el contexto de build
COPY ./server/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Puerto por defecto para el gRPC
# El 50050 es el puerto por defecto, pero se puede cambiar con la variable de entorno SERVER_GRPC_PORT
EXPOSE 50050

# Usar entrypoint para comprobar variables 
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Comando para ejecutar la aplicación
CMD ["node", "src/api.js"]

# Ejemplo de comando para construir la imagen:
# podman build -f containerfile -t nombre-imagen . 

# Ejemplo podman-compose.yaml:
# version: "3.9"
# services:
#   db-server-c:
#     image: postgres:16.8-alpine3.20
#     container_name: db-server-c
#     environment:
#       POSTGRES_USER: user-c
#       POSTGRES_PASSWORD: 12345
#       POSTGRES_DB: db-c
#       PGDATA: /var/lib/postgresql/data/pgdata
#     ports:
#       - 4002:5432
#     volumes:
#       - ./db-c:/var/lib/postgresql/data/pgdata:Z
#       - ./c-init.sql:/docker-entrypoint-initdb.d/c-init.sql:Z

#   node-server-c:
#     image: nombre-imagen
#     container_name: server-c
#     working_dir: /app
#     environment:
#       DB_HOST: db-server-c
#       DB_PORT: 5432
#       DB_USER: user-c
#       DB_PASSWORD: 12345
#       DB_NAME: db-c
#       # Variables de entorno para la aplicación es opcional por default es 50050
#       SERVER_GRPC_PORT: 50055
#       # en localhost debe colocar la IP del host donde se ejecutan los servicios gRPC
#       PEDIDOS_GRPC_IP_PORT: localhost:50051
#     ports:
#       - "50052:50055"
#     depends_on:
#       - db-server-c
