version: "3"

services:
  db-server-c:
    image: postgres:16.8-alpine3.20
    container_name: db-server-c
    environment:
      POSTGRES_USER: user-c
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db-c
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 3003:5432
    volumes:
      - ./db-c:/var/lib/postgresql/data/pgdata:Z
      - ./c-init.sql:/docker-entrypoint-initdb.d/c-init.sql:Z

  node-server-c:
    image: node:alpine
    container_name: node-server-c
    working_dir: /app
    volumes:
      - ./server:/app:Z
    environment:
      DB_HOST: "db-server-c"
      DB_PORT: "5432"
      DB_USER: "user-c"
      DB_PASSWORD: "12345"
      DB_NAME: "db-c"
      # El puerto del contenedor node
      SERVER_GRPC_PORT: "50052"
      # En localhost hay que local la IP del servidor Grpc 
      PEDIDOS_GRPC_IP_PORT: "localhost:50051"
    command: sh -c "npm install && node --run dev"
    ports:
      - "50052:50052"
    depends_on:
      - db-server-c
