version: "3"

services:
  db-server-a:
    image: mariadb:11
    container_name: db-server-a
    environment:
      MARIADB_ROOT_PASSWORD: 12345
      MARIADB_USER: user-a
      MARIADB_PASSWORD: 12345
      MARIADB_DATABASE: db-a
    ports:
      - "3001:3306"
    volumes:
      - ./db-a:/var/lib/mysql:Z
      - ./a-init.sql:/docker-entrypoint-initdb.d/a-init.sql:Z

  node-server-a:
    image: node:alpine
    container_name: node-server-a
    working_dir: /app
    volumes:
      - ./server:/app:Z
    environment:
      DB_HOST: "db-server-a"
      DB_PORT: "3306"
      DB_USER: "user-a"
      DB_PASSWORD: "12345"
      DB_NAME: "db-a"
      # El puerto del contenedor node
      SERVER_GRPC_PORT: "50050"
      # En localhost hay que local la IP del servidor Grpc 
      PEDIDOS_GRPC_IP_PORT: "localhost:50051"
    command: sh -c "npm install && node --run dev"
    ports:
      - "50050:50050"
    depends_on:
      - db-server-a
