version: "3"

services:
  db-server-b:
    image: mysql:lts
    container_name: db-server-b
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user-b
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: db-b
    ports:
      - 3002:3306
    volumes:
      - ./db-b:/var/lib/mysql:Z
      - ./b-init.sql:/docker-entrypoint-initdb.d/b-init.sql:Z

  node-server-b:
    image: node:alpine
    container_name: node-server-b
    working_dir: /app
    volumes:
      - ./server:/app:Z
    environment:
      DB_HOST: "db-server-b"
      DB_PORT: "3306"
      DB_USER: "user-b"
      DB_PASSWORD: "12345"
      DB_NAME: "db-b"
      SERVER_GRPC_PORT: "50051"
      CLIENTES_GRPC_IP_PORT: "192.168.1.20:50050"
      PRODUCTOS_GRPC_IP_PORT: "192.168.1.20:50052"
    command: sh -c "npm install && node --run dev"
    ports:
      - "50051:50051"
    depends_on:
      - db-server-b
