version: "3"

services:
  server-b:
    image: mysql:lts
    container_name: db-server-b
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user-b
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: db-b
    ports:
      - 3002:3306
    volumes:
      - ./db-b:/var/lib/mysql:Z
      - ./b-init.sql:/docker-entrypoint-initdb.d/b-init.sql:Z
