# Containerfile para el servicio api-server (validación de variables en runtime)

# Imagen base
FROM node:lts-alpine3.21

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar solo package.json y package-lock.json para caché inteligente
COPY ./server/package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY ./server ./

# Copiar script de entrada para validar variables de entorno
# Asegúrate de colocar entrypoint.sh dentro de la carpeta 'server' para incluirlo en el contexto de build
COPY ./server/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Exponer el puerto (se debe pasar EXPRESS_PORT al runtime)
EXPOSE 3000

# Usar entrypoint para comprobar variables 
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Comando para ejecutar la aplicación
CMD ["node", "src/api.js"]

# Ejemplo de comando para construir la imagen:
# podman build -f containerfile -t nombre-imagen . 

# Ejemplo de podman-compose.yaml:
# version: "3.9"
# services:
#   api-server:
#     image: nombre-imagen
#     environment:
#       # Variables de entorno para la aplicación es opcional por default es 3000
#       EXPRESS_PORT: 3500 
#       # en localhost debe colocar la IP del host donde se ejecutan los servicios gRPC
#       CLIENTES_GRPC_IP_PORT: localhost:50050
#       PEDIDOS_GRPC_IP_PORT: localhost:50051
#       PRODUCTOS_GRPC_IP_PORT: localhost:50052
#     ports:
#       - "3000:3500"
    
