vercion: "3"

services:
  api-server:
    image: node:alpine
    container_name: api-server
    working_dir: /app
    volumes:
      - ./server:/app:Z
    environment:
      # El puerto del contenedor node
      EXPRESS_PORT: "3000"
      # En 192.168.1.20 hay que local la IP del servidor Grpc
      CLIENTES_GRPC_IP_PORT: "192.168.1.20:50050" 
      PEDIDOS_GRPC_IP_PORT: "192.168.1.20:50051"
      PRODUCTOS_GRPC_IP_PORT: "192.168.1.20:50052"
    command: sh -c "npm install && node --run dev"
    ports:
      - "3000:3000"